name: JamaicaDeals

options:
  bundleIdPrefix: com.jamesbaker
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15"

packages:
  GoogleMobileAds:
    url: https://github.com/googleads/swift-package-manager-google-mobile-ads
    from: "11.0.0"
  FirebaseSDK:
    url: https://github.com/firebase/firebase-ios-sdk
    from: "11.0.0"

targets:
  JamaicaDeals:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: JamaicaVacationDeals
        excludes:
          - "**/.DS_Store"
    info:
      path: JamaicaVacationDeals/Info.plist
      properties:
        CFBundleDisplayName: JamaicaDeals
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
        CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"
        UILaunchScreen:
          UIColorName: ""
          UIImageName: ""
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        ITSAppUsesNonExemptEncryption: false
        GADApplicationIdentifier: "ca-app-pub-3940256099942544~1458002511"
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
        SKAdNetworkItems:
          - SKAdNetworkIdentifier: cstr6suwn9.skadnetwork
          - SKAdNetworkIdentifier: 4fzdc2evr5.skadnetwork
          - SKAdNetworkIdentifier: 2fnua5tdw4.skadnetwork
          - SKAdNetworkIdentifier: ydx93a7ass.skadnetwork
    dependencies:
      - package: GoogleMobileAds
        product: GoogleMobileAds
      - package: FirebaseSDK
        product: FirebaseAnalytics
      - package: FirebaseSDK
        product: FirebaseCore
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.jamesbaker.jamaicadeals
      SWIFT_VERSION: "5.9"
      TARGETED_DEVICE_FAMILY: "1,2"
      DEVELOPMENT_TEAM: ""
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      MARKETING_VERSION: "1.0"
      CURRENT_PROJECT_VERSION: "1"
